### ISSUE TITLE
Rename "Views" directory

### ISSUE THREAD

**Issue by timarney** [cds-snc/node-starter-app#71]
Up for discussion ...

After talking to @sastels and @smcmurtry I think we need to change the name of the "views" directory as it doesn't contain all the views for the app.

That dir contains the the "global" layouts and app macros ... but now the route "views".

Thoughts on a better name for that dir?

cc: @dsamojlenko @maxneuvians

**Comment by dsamojlenko** [comment]
Maybe `templates`?

If we're going to open up a discussion on directory structure again, I had another idea back when we moved the sass files out of public to assets... I thought maybe some of these things should actually be grouped under resources.

ie, 

resources/assets/sass
resources/assets/js
resources/templates
resources/locales
 
under resources/assets we could also include js files that could be minified and combined and dumped into public by middleware.

...or just rename views to templates 🤷‍♂

**Comment by timarney** [comment]
I like the idea maybe moving under assets would do the trick:
```
assets/sass
assets/js
assets/templates
```

Thinking locales should be keep separate 🤷‍♂

**Comment by timarney** [comment]
@dsamojlenko let's park this as not needed for now.
