### ISSUE TITLE
Language setting is lost after 2 navigation clicks

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/node-starter-app#74]
If I select french on the landing page, then click to the next page, it is in french but the `lang` query param has been lost. So then when I click to the next next page it is in english. 

One way to fix this would be to add a utility function that adds the query params from the current page to the next route. This would have to be set both for the `nextRoute` variable that is passed to the template, and the redirect that the middleware does when a post request is submitted from a form page.

**Comment by smcmurtry** [comment]
Here's my attempt to fix this: https://github.com/cds-snc/simplify-privacy-statements-V2/pull/34

Could probably be generalized better.

**Comment by dsamojlenko** [comment]
Fixed in #78
