### ISSUE TITLE
View Engine

### ISSUE THREAD

**Issue by timarney** [cds-snc/node-starter-app#9]
As a group we should decide what view engine we want to use as the default.

The current setup uses [PUG](https://pugjs.org/api/getting-started.html).  If we prefer writing closer to html [Handlebars](https://handlebarsjs.com) might be a better option.

We'll stick with PUG for now,

Please suggest what you would prefer and why.

**Things to keep in mind**
- learning curve
- vulnerabilities / patch cycles
- flexibility 
- community outside of CDS adoption
- future roadmap (active contributions)

**Comment by dsamojlenko** [comment]
#15

**Comment by timarney** [comment]
The masses have voted for Nunjucks.
