### ISSUE TITLE
Saving all form values will potentially save the redirect value and csrf token

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/node-starter-app#93]
Hello!

Without doing a ton of investigating, it looks like [your session helper over here is saving all form data to the session](https://github.com/cds-snc/node-starter-app/blob/master/utils/session.helpers.js#L6-L10). That's cool, and we do it too.

However, [we have some middleware that does something similar except it also removes the `redirect` key](https://github.com/cds-snc/cra-claim-tax-benefits/blob/master/utils/index.js#L92-L94) -- it's on lots of our forms but we don't want to save it.

- copy the form values to a new object (don't want to mutate our data)
- delete `redirect` (won't throw an error if it works)

So yeah, close the issue if you want or I can do a PR with a few tests if you're interested.

**Comment by timarney** [comment]
👍 At some point I want to add a check the Schema(s) for allowed values but that's down the road - thanks for the PR.
