### ISSUE TITLE
Required fields markers

### ISSUE THREAD

**Issue by CalvinRodo** [cds-snc/node-starter-app#98]
So while the [Form Design from Zero to Hero blog post ](https://adamsilver.io/articles/form-design-from-zero-to-hero-all-in-one-blog-post ) states that you shouldn't mark fields as required it is a requirement at ESDC to pass our accessibility guidelines. 

And while the [success criterion for 3.3.2](https://www.w3.org/WAI/WCAG20/quickref/20160105/#minimize-error-cues) states that: 

> G131: Providing descriptive labels AND one of the following:
    - ARIA1: Using the aria-describedby property to provide a descriptive label for user interface controls (ARIA)
    - ARIA9: Using aria-labelledby to concatenate a label from several text nodes (ARIA)
    - ARIA17: Using grouping roles to identify related form controls (ARIA)
    - G89: Providing expected data format and example
    - G184: Providing text instructions at the beginning of a form or set of fields that describes the necessary input
    - G162: Positioning labels to maximize predictability of relationships
    - G83: Providing text descriptions to identify required fields that were not completed
    - H90: Indicating required form controls using label or legend (HTML)
    - FLASH10: Indicating required form controls in Flash (Flash)
     - PDF5: Indicating required form controls in PDF forms (PDF) 

We don't have the luxury of not having required fields, so would be nice to have them in the starter-app or at least the option to render them for those that can exclude them.

**Comment by timarney** [comment]
Thanks @CalvinRodo happy to accommodate.  In practice what does this typically look like for your forms (screenshot would help).

i.e. not seeing them in bio metrics app i.e.
<img width="550" alt="Screen Shot 2019-10-08 at 12 15 47 PM" src="https://user-images.githubusercontent.com/62242/66413443-64c56d00-e9c5-11e9-8063-4d2d85800c55.png">

I would be very much for a minimum making that an option - but ideally something that works for everyone. 

cc: @JuliannaR

**Comment by timarney** [comment]
More like this perhaps

http://www.cic.gc.ca/english/passport/map/map.asp

<img width="729" alt="Screen Shot 2019-10-08 at 12 20 57 PM" src="https://user-images.githubusercontent.com/62242/66413929-617eb100-e9c6-11e9-9ec4-88852cb90922.png">

**Comment by CalvinRodo** [comment]
The web experience toolkit style guide is a good example for our stuff since that's what most of our stuff is built on.

Their form validation demo outlines how our forms look
https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html

The biometric scheduler needs some work to align with ESDC standards.

**Comment by timarney** [comment]
Noting this pattern from GOV.UK 

https://govuk-elements.herokuapp.com/form-elements/#form-optional-fields

 cc: @obrien-j 


```
- if you do ask for optional information, mark the labels of optional fields with ‘(optional)’
- don’t mark mandatory fields with asterisks
```

Will look at what making that an option available as opt-in to would look like.

**Comment by timarney** [comment]
@willeybryan flagging this as a todo item after yesterdays chat with @JuliannaR .

We'll plan to make this available as an option.

Noting > per Julianna it's easier for screen readers users find the required fields if they are marked as such vs 1. not revealing until clicked or 2. marking optional fields.

**Comment by timarney** [comment]
PR merged here:
https://github.com/cds-snc/node-starter-app/pull/107
